name: "Assemble"
description: "Build the project and run local tests"

runs:
  using: 'composite'
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    # Local properties write in local.properties
    - name: Setup local.properties
      run: |
        bash ./scripts/check_api_key.sh

    # Decode keystore file encoded by base64
    - name: Decode Keystore
      run: |
        echo ${{ secrets.KEYSTORE }} | base64 --d > keystore.jks

    # Keystore properties write in keystore.properties
    - name: Set up keystore.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" >> keystore.properties  
        echo "storeFile=`pwd`/keystore.jks" >> ./keystore.properties

    - name: Set up service account key json
      run: |
        echo ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }} | base64 --d > app/fireframe-service-account-key.json

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-assemble-action@v3

    - name: Check spotless
      run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

    # Run tests assemble
    - name: Run local tests
      run: ./gradlew testDebugUnitTest --stacktrace

    # Create APK and AAB
    - name: Build all assemble type and flavor permutations
      run: |
        ./gradlew :app:assemble
        ./gradlew :app:bundle