# https://github.com/takahirom/roborazzi-compare-on-github-comment-sample/blob/main/.github/workflows/CompareScreenshot.yml

name: CompareScreenshot

on:
  pull_request:

jobs:
  compare-screenshot-test:
    name: "Compare Screenshot"
    runs-on: ubuntu-latest

    timeout-minutes: 20

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Local properties write in local.properties
      - name: Setup local.properties
        env:
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        run: |
          bash ./scripts/check_api_key.sh

      # Decode google-services.json encoded by base64 for firebase
      - name: Decode Google Services Json
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 --d > ./app/google-services.json

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Download screenshot
        uses: dawidd6/action-download-artifact@v7
        continue-on-error: true
        with:
          name: screenshot
          workflow: StoreScreenshot.yml
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}

      - name: Compare screenshot test
        id: compare-screenshot-test
        run: ./gradlew compareRoborazziDebug --stacktrace

      - name: Upload screenshot diff
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Upload screenshot diff reports
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-diff-reports
          path: |
            **/build/reports
          retention-days: 30

      - name: Upload screenshot diff test results
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-diff-test-results
          path: |
            **/build/test-results
          retention-days: 30

      - name: Save PullRequest number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - name: Upload PullRequest number
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/