name: PublishGoogle

on:
  workflow_dispatch:

jobs:
  publish_google:
    name: "Publish Google Play"
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Action
        uses: ./.github/actions/Build

      # Upload build outputs (APKs and AABs)
      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: APKs and AABs
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
            **/build/outputs/mapping/**/*.txt
          retention-days: 1

      # Publish build outputs (AAB) to Google Play
      - name: Publish Google Play
        run: |
          echo "Publish Google Play"
          ./gradlew publishReleaseBundle --artifact-dir app/build/outputs/bundle/release