name: PublishAmazon

on:
  workflow_dispatch:

jobs:
  publish_amazon:
    name: "Publish Amazon Appstore"
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Action
        uses: ./.github/actions/assemble
        with:
          encoded_keystore: ${{ secrets.KEYSTORE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          keystore_alias: ${{ secrets.KEYSTORE_ALIAS }}
          open_weather_api_key: ${{ secrets.OPEN_WEATHER_API_KEY }}
          encoded_google_services_json: ${{ secrets.GOOGLE_SERVICES_JSON }}

      # Upload build outputs (APKs and AABs)
      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: APKs and AABs
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
            **/build/outputs/mapping/**/*.txt
          retention-days: 1

      # Publish build outputs (APK) to Amazon Appstore
      - name: Publish Release APK
        env:
          CLIENT_ID: ${{ secrets.AMAZON_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AMAZON_CLIENT_SECRET }}
          APP_ID: ${{ secrets.AMAZON_APP_ID }}
        run: |
          bash ./scripts/amazon_submission.sh
        shell: bash