# https://github.com/takahirom/roborazzi-compare-on-github-comment-sample/blob/main/.github/workflows/StoreScreenshot.yml

name: StoreScreenshot

env:
  open_weather_api_key: ${{ secrets.OPEN_WEATHER_API_KEY }}

on:
  push:
    branches:
      - main

jobs:
  store-screenshot-test:
    name: "Store Screenshot"
    runs-on: ubuntu-latest

    timeout-minutes: 20

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Local properties write in local.properties
      - name: Setup local.properties
        run: |
          bash ./scripts/check_api_key.sh

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Record screenshot
        run: ./gradlew recordRoborazziDebug --stacktrace --rerun-tasks

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Upload screenshot reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-reports
          path: |
            **/build/reports
          retention-days: 30

      - name: Upload screenshot test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-test-results
          path: |
            **/build/test-results
          retention-days: 30
